// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWGWSqcCMBT__sTSrDvRi0iEozY20TcyA',
    appId: '1:120922277909:web:a3061e4cd9e75e8cc0661c',
    messagingSenderId: '120922277909',
    projectId: 'fir-project-368b2',
    authDomain: 'fir-project-368b2.firebaseapp.com',
    storageBucket: 'fir-project-368b2.appspot.com',
    measurementId: 'G-NSKWD5Z3LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmtVSC9RInKE_l3cEwj2cDJBvyCzrEsWw',
    appId: '1:120922277909:android:bd330885073c5549c0661c',
    messagingSenderId: '120922277909',
    projectId: 'fir-project-368b2',
    storageBucket: 'fir-project-368b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcnK4CICgKcy5JkgTiwq9_hXC2WizMRjc',
    appId: '1:120922277909:ios:2b9dd48284a3d0ebc0661c',
    messagingSenderId: '120922277909',
    projectId: 'fir-project-368b2',
    storageBucket: 'fir-project-368b2.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcnK4CICgKcy5JkgTiwq9_hXC2WizMRjc',
    appId: '1:120922277909:ios:02e1e6f7193872a0c0661c',
    messagingSenderId: '120922277909',
    projectId: 'fir-project-368b2',
    storageBucket: 'fir-project-368b2.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
